package com.hiresemble.agentrun.domain.model;

public enum WorkflowType {
    DOCUMENT_INGESTION,
    JOB_POSTING_EXTRACTION,
    JOB_ANALYSIS,
    COVER_LETTER_GENERATION,
    COVER_LETTER_VERIFICATION,
    INTERVIEW_PREPARATION,
    INTERVIEW_ANSWER_FEEDBACK,
    MOCK_INTERVIEW_FEEDBACK
}
